### ISSUE TITLE
Eigen/gtsam error when solving linear system

### ISSUE THREAD

**Issue by YoshuaNava** [lorenwel/linefit_ground_segmentation#7]
Hi,
When I try to use a GroundSegmentation object, along with a SegMatchWorker from [SegMap](https://github.com/ethz-asl/segmap) for my algorithm, I get an error with the following backtrace:

```
0x00007ffff767643a in Eigen::internal::gebp_kernel<double, double, long, 4, 4, false, false>::operator()(double*, long, double const*, double const*, long, long, long, double, long, long, long, long, double*) [clone .constprop.1215] ()
   from /home/alfredoso/Robotics/Dependencies/asl_depends_ws/devel/lib/libgtsam.so.4
(gdb) bt
#0  0x00007ffff767643a in Eigen::internal::gebp_kernel<double, double, long, 4, 4, false, false>::operator()(double*, long, double const*, double const*, long, long, long, double, long, long, long, long, double*) [clone .constprop.1215] ()
   from /home/alfredoso/Robotics/Dependencies/asl_depends_ws/devel/lib/libgtsam.so.4
#1  0x00007ffff7695c55 in Eigen::internal::general_matrix_matrix_product<long, double, 0, false, double, 0, false, 0>::run(long, long, long, double const*, long, double const*, long, double*, long, double, Eigen::internal::level3_blocking<double, double>&, Eigen::internal::GemmParallelInfo<long>*) () from /home/alfredoso/Robotics/Dependencies/asl_depends_ws/devel/lib/libgtsam.so.4
#2  0x00007ffff4342ec2 in Eigen::internal::gemm_functor<double, long, Eigen::internal::general_matrix_matrix_product<long, double, 0, false, double, 0, false, 0>, Eigen::Matrix<double, -1, -1, 0, -1, -1>, Eigen::Matrix<double, -1, -1, 0, -1, -1>, Eigen::Matrix<double, -1, -1, 0, -1, -1>, Eigen::internal::gemm_blocking_space<0, double, double, -1, -1, -1, 1, false> >::operator() (info=0x0, cols=<optimized out>, col=0, rows=<optimized out>, row=0, this=<optimized out>)
    at /usr/include/eigen3/Eigen/src/Core/products/GeneralMatrixMatrix.h:229
#3  Eigen::internal::parallelize_gemm<true, Eigen::internal::gemm_functor<double, long, Eigen::internal::general_matrix_matrix_product<long, double, 0, false, double, 0, false, 0>, Eigen::Matrix<double, -1, -1, 0, -1, -1>, Eigen::Matrix<double, -1, -1, 0, -1, -1>, Eigen::Matrix<double, -1, -1, 0, -1, -1>, Eigen::internal::gemm_blocking_space<0, double, double, -1, -1, -1, 1, false> >, long> (transpose=false, cols=<optimized out>, rows=<optimized out>, func=...) at /usr/include/eigen3/Eigen/src/Core/products/Parallelizer.h:96
#4  Eigen::internal::generic_product_impl<Eigen::Matrix<double, -1, -1, 0, -1, -1>, Eigen::Matrix<double, -1, -1, 0, -1, -1>, Eigen::DenseShape, Eigen::DenseShape, 8>::scaleAndAddTo<Eigen::Matrix<double, -1, -1, 0, -1, -1> > (alpha=<optimized out>, a_rhs=..., 
    a_lhs=..., dst=...) at /usr/include/eigen3/Eigen/src/Core/products/GeneralMatrixMatrix.h:487
#5  Eigen::internal::generic_product_impl<Eigen::Matrix<double, -1, -1, 0, -1, -1>, Eigen::Matrix<double, -1, -1, 0, -1, -1>, Eigen::DenseShape, Eigen::DenseShape, 8>::evalTo<Eigen::Matrix<double, -1, -1, 0, -1, -1> > (rhs=..., lhs=..., dst=...)
    at /usr/include/eigen3/Eigen/src/Core/products/GeneralMatrixMatrix.h:439
#6  Eigen::internal::Assignment<Eigen::Matrix<double, -1, -1, 0, -1, -1>, Eigen::Product<Eigen::Matrix<double, -1, -1, 0, -1, -1>, Eigen::Matrix<double, -1, -1, 0, -1, -1>, 0>, Eigen::internal::assign_op<double>, Eigen::internal::Dense2Dense, double>::run (src=..., 
    dst=...) at /usr/include/eigen3/Eigen/src/Core/ProductEvaluators.h:133
#7  Eigen::internal::call_assignment_no_alias<Eigen::Matrix<double, -1, -1, 0, -1, -1>, Eigen::Product<Eigen::Matrix<double, -1, -1, 0, -1, -1>, Eigen::Matrix<double, -1, -1, 0, -1, -1>, 0>, Eigen::internal::assign_op<double> > (func=..., src=..., dst=...)
    at /usr/include/eigen3/Eigen/src/Core/AssignEvaluator.h:747
#8  Eigen::PlainObjectBase<Eigen::Matrix<double, -1, -1, 0, -1, -1> >::_set_noalias<Eigen::Product<Eigen::Matrix<double, -1, -1, 0, -1, -1>, Eigen::Matrix<double, -1, -1, 0, -1, -1>, 0> > (other=..., this=0x7fff8f7f62c0)
    at /usr/include/eigen3/Eigen/src/Core/PlainObjectBase.h:700
#9  Eigen::PlainObjectBase<Eigen::Matrix<double, -1, -1, 0, -1, -1> >::_init1<Eigen::Product<Eigen::Matrix<double, -1, -1, 0, -1, -1>, Eigen::Matrix<double, -1, -1, 0, -1, -1>, 0>, Eigen::Product<Eigen::Matrix<double, -1, -1, 0, -1, -1>, Eigen::Matrix<double, -1, -1, 0, -1, -1>, 0> > (other=..., this=0x7fff8f7f62c0) at /usr/include/eigen3/Eigen/src/Core/PlainObjectBase.h:783
#10 Eigen::Matrix<double, -1, -1, 0, -1, -1>::Matrix<Eigen::Product<Eigen::Matrix<double, -1, -1, 0, -1, -1>, Eigen::Matrix<double, -1, -1, 0, -1, -1>, 0> > (x=..., this=0x7fff8f7f62c0) at /usr/include/eigen3/Eigen/src/Core/Matrix.h:296
#11 Eigen::internal::Assignment<Eigen::Matrix<double, -1, -1, 0, -1, -1>, Eigen::Inverse<Eigen::Product<Eigen::Matrix<double, -1, -1, 0, -1, -1>, Eigen::Matrix<double, -1, -1, 0, -1, -1>, 0> >, Eigen::internal::assign_op<double>, Eigen::internal::Dense2Dense, double>::run (src=..., dst=...) at /usr/include/eigen3/Eigen/src/LU/InverseImpl.h:304
#12 Eigen::internal::call_assignment_no_alias<Eigen::Matrix<double, -1, -1, 0, -1, -1>, Eigen::Inverse<Eigen::Product<Eigen::Matrix<double, -1, -1, 0, -1, -1>, Eigen::Matrix<double, -1, -1, 0, -1, -1>, 0> >, Eigen::internal::assign_op<double> > (dst=..., src=..., 
    func=...) at /usr/include/eigen3/Eigen/src/Core/AssignEvaluator.h:747
#13 0x00007ffff4343d3e in Eigen::PlainObjectBase<Eigen::Matrix<double, -1, -1, 0, -1, -1> >::_set_noalias<Eigen::Inverse<Eigen::Product<Eigen::Matrix<double, -1, -1, 0, -1, -1>, Eigen::Matrix<double, -1, -1, 0, -1, -1>, 0> > > (other=..., this=0x7fff8f7f6520)
    at /usr/include/eigen3/Eigen/src/Core/PlainObjectBase.h:700
#14 Eigen::PlainObjectBase<Eigen::Matrix<double, -1, -1, 0, -1, -1> >::PlainObjectBase<Eigen::Inverse<Eigen::Product<Eigen::Matrix<double, -1, -1, 0, -1, -1>, Eigen::Matrix<double, -1, -1, 0, -1, -1>, 0> > > (other=..., this=0x7fff8f7f6520)
    at /usr/include/eigen3/Eigen/src/Core/PlainObjectBase.h:510
#15 Eigen::Matrix<double, -1, -1, 0, -1, -1>::Matrix<Eigen::Inverse<Eigen::Product<Eigen::Matrix<double, -1, -1, 0, -1, -1>, Eigen::Matrix<double, -1, -1, 0, -1, -1>, 0> > > (other=..., this=0x7fff8f7f6520) at /usr/include/eigen3/Eigen/src/Core/Matrix.h:379
#16 Eigen::internal::generic_product_impl<Eigen::Inverse<Eigen::Product<Eigen::Matrix<double, -1, -1, 0, -1, -1>, Eigen::Matrix<double, -1, -1, 0, -1, -1>, 0> >, Eigen::Matrix<double, -1, -1, 0, -1, -1>, Eigen::DenseShape, Eigen::DenseShape, 8>::scaleAndAddTo<Eigen::Matrix<double, -1, -1, 0, -1, -1> > (alpha=<optimized out>, a_rhs=..., a_lhs=..., dst=...) at /usr/include/eigen3/Eigen/src/Core/products/GeneralMatrixMatrix.h:468
#17 Eigen::internal::generic_product_impl<Eigen::Inverse<Eigen::Product<Eigen::Matrix<double, -1, -1, 0, -1, -1>, Eigen::Matrix<double, -1, -1, 0, -1, -1>, 0> >, Eigen::Matrix<double, -1, -1, 0, -1, -1>, Eigen::DenseShape, Eigen::DenseShape, 8>::evalTo<Eigen::Matrix<double, -1, -1, 0, -1, -1> > (rhs=..., lhs=..., dst=...) at /usr/include/eigen3/Eigen/src/Core/products/GeneralMatrixMatrix.h:439
#18 Eigen::internal::product_evaluator<Eigen::Product<Eigen::Inverse<Eigen::Product<Eigen::Matrix<double, -1, -1, 0, -1, -1>, Eigen::Matrix<double, -1, -1, 0, -1, -1>, 0> >, Eigen::Matrix<double, -1, -1, 0, -1, -1>, 0>, 8, Eigen::DenseShape, Eigen::DenseShape, double, double>::product_evaluator (xpr=..., this=0x7fff8f7f65d0) at /usr/include/eigen3/Eigen/src/Core/ProductEvaluators.h:117
#19 Eigen::internal::evaluator<Eigen::Product<Eigen::Inverse<Eigen::Product<Eigen::Matrix<double, -1, -1, 0, -1, -1>, Eigen::Matrix<double, -1, -1, 0, -1, -1>, 0> >, Eigen::Matrix<double, -1, -1, 0, -1, -1>, 0> >::evaluator (xpr=..., this=0x7fff8f7f65d0)
    at /usr/include/eigen3/Eigen/src/Core/ProductEvaluators.h:35
#20 Eigen::internal::evaluator<Eigen::Product<Eigen::Inverse<Eigen::Product<Eigen::Matrix<double, -1, -1, 0, -1, -1>, Eigen::Matrix<double, -1, -1, 0, -1, -1>, 0> >, Eigen::Matrix<double, -1, -1, 0, -1, -1>, 0> const>::evaluator (xpr=..., this=0x7fff8f7f65d0)
    at /usr/include/eigen3/Eigen/src/Core/CoreEvaluators.h:94
#21 Eigen::internal::unary_evaluator<Eigen::Block<Eigen::Product<Eigen::Inverse<Eigen::Product<Eigen::Matrix<double, -1, -1, 0, -1, -1>, Eigen::Matrix<double, -1, -1, 0, -1, -1>, 0> >, Eigen::Matrix<double, -1, -1, 0, -1, -1>, 0> const, -1, 1, true>, Eigen::internal::IndexBased, double>::unary_evaluator (block=..., this=0x7fff8f7f65c8) at /usr/include/eigen3/Eigen/src/Core/CoreEvaluators.h:760
#22 Eigen::internal::block_evaluator<Eigen::Product<Eigen::Inverse<Eigen::Product<Eigen::Matrix<double, -1, -1, 0, -1, -1>, Eigen::Matrix<double, -1, -1, 0, -1, -1>, 0> >, Eigen::Matrix<double, -1, -1, 0, -1, -1>, 0> const, -1, 1, true, false>::block_evaluator (
    block=..., this=0x7fff8f7f65c8) at /usr/include/eigen3/Eigen/src/Core/CoreEvaluators.h:747
#23 Eigen::internal::evaluator<Eigen::Block<Eigen::Product<Eigen::Inverse<Eigen::Product<Eigen::Matrix<double, -1, -1, 0, -1, -1>, Eigen::Matrix<double, -1, -1, 0, -1, -1>, 0> >, Eigen::Matrix<double, -1, -1, 0, -1, -1>, 0> const, -1, 1, true> >::evaluator (block=..., 
    this=0x7fff8f7f65c8) at /usr/include/eigen3/Eigen/src/Core/CoreEvaluators.h:733
#24 Eigen::internal::evaluator<Eigen::Block<Eigen::Product<Eigen::Inverse<Eigen::Product<Eigen::Matrix<double, -1, -1, 0, -1, -1>, Eigen::Matrix<double, -1, -1, 0, -1, -1>, 0> >, Eigen::Matrix<double, -1, -1, 0, -1, -1>, 0> const, -1, 1, true> const>::evaluator (
    xpr=..., this=0x7fff8f7f65c8) at /usr/include/eigen3/Eigen/src/Core/CoreEvaluators.h:94
#25 Eigen::internal::unary_evaluator<Eigen::CwiseUnaryOp<Eigen::internal::scalar_multiple_op<double>, Eigen::Block<Eigen::Product<Eigen::Inverse<Eigen::Product<Eigen::Matrix<double, -1, -1, 0, -1, -1>, Eigen::Matrix<double, -1, -1, 0, -1, -1>, 0> >, Eigen::Matrix<double, -1, -1, 0, -1, -1>, 0> const, -1, 1, true> const>, Eigen::internal::IndexBased, double>::unary_evaluator (op=..., this=0x7fff8f7f65c0) at /usr/include/eigen3/Eigen/src/Core/CoreEvaluators.h:385
#26 Eigen::internal::evaluator<Eigen::CwiseUnaryOp<Eigen::internal::scalar_multiple_op<double>, Eigen::Block<Eigen::Product<Eigen::Inverse<Eigen::Product<Eigen::Matrix<double, -1, -1, 0, -1, -1>, Eigen::Matrix<double, -1, -1, 0, -1, -1>, 0> >, Eigen::Matrix<double, -1, -1, 0, -1, -1>, 0> const, -1, 1, true> const> >::evaluator (xpr=..., this=0x7fff8f7f65c0) at /usr/include/eigen3/Eigen/src/Core/CoreEvaluators.h:84
#27 Eigen::internal::call_dense_assignment_loop<Eigen::Matrix<double, -1, 1, 0, -1, 1>, Eigen::CwiseUnaryOp<Eigen::internal::scalar_multiple_op<double>, Eigen::Block<Eigen::Product<Eigen::Inverse<Eigen::Product<Eigen::Matrix<double, -1, -1, 0, -1, -1>, Eigen::Matrix<double, -1, -1, 0, -1, -1>, 0> >, Eigen::Matrix<double, -1, -1, 0, -1, -1>, 0> const, -1, 1, true> const>, Eigen::internal::add_assign_op<double> > (func=..., src=..., dst=...) at /usr/include/eigen3/Eigen/src/Core/AssignEvaluator.h:648
#28 Eigen::internal::Assignment<Eigen::Matrix<double, -1, 1, 0, -1, 1>, Eigen::CwiseUnaryOp<Eigen::internal::scalar_multiple_op<double>, Eigen::Block<Eigen::Product<Eigen::Inverse<Eigen::Product<Eigen::Matrix<double, -1, -1, 0, -1, -1>, Eigen::Matrix<double, -1, -1, 0, -1, -1>, 0> >, Eigen::Matrix<double, -1, -1, 0, -1, -1>, 0> const, -1, 1, true> const>, Eigen::internal::add_assign_op<double>, Eigen::internal::Dense2Dense, double>::run (func=..., src=..., dst=...) at /usr/include/eigen3/Eigen/src/Core/AssignEvaluator.h:790
#29 Eigen::internal::call_assignment_no_alias<Eigen::Matrix<double, -1, 1, 0, -1, 1>, Eigen::CwiseUnaryOp<Eigen::internal::scalar_multiple_op<double>, Eigen::Block<Eigen::Product<Eigen::Inverse<Eigen::Product<Eigen::Matrix<double, -1, -1, 0, -1, -1>, Eigen::Matrix<double, -1, -1, 0, -1, -1>, 0> >, Eigen::Matrix<double, -1, -1, 0, -1, -1>, 0> const, -1, 1, true> const>, Eigen::internal::add_assign_op<double> > (func=..., src=..., dst=...) at /usr/include/eigen3/Eigen/src/Core/AssignEvaluator.h:747
#30 Eigen::internal::call_assignment<Eigen::Matrix<double, -1, 1, 0, -1, 1>, Eigen::CwiseUnaryOp<Eigen::internal::scalar_multiple_op<double>, Eigen::Block<Eigen::Product<Eigen::Inverse<Eigen::Product<Eigen::Matrix<double, -1, -1, 0, -1, -1>, Eigen::Matrix<double, -1, -1, 0, -1, -1>, 0> >, Eigen::Matrix<double, -1, -1, 0, -1, -1>, 0> const, -1, 1, true> const>, Eigen::internal::add_assign_op<double> >(Eigen::Matrix<double, -1, 1, 0, -1, 1>&, Eigen::CwiseUnaryOp<Eigen::internal::scalar_multiple_op<double>, Eigen::Block<Eigen::Product<Eigen::Inverse<Eigen::Product<Eigen::Matrix<double, -1, -1, 0, -1, -1>, Eigen::Matrix<double, -1, -1, 0, -1, -1>, 0> >, Eigen::Matrix<double, -1, -1, 0, -1, -1>, 0> const, -1, 1, true> const> const&, Eigen::internal::add_assign_op<double> const&, Eigen::internal::enable_if<!Eigen::internal::evaluator_assume_aliasing<Eigen::CwiseUnaryOp<Eigen::internal::scalar_multiple_op<double>, Eigen::Block<Eigen::Product<Eigen::Inverse<Eigen::Product<Eigen::Matrix<double, -1, -1, 0, -1, -1>, Eigen::Matrix<double, -1, -1, 0, -1, -1>, 0> >, Eigen::Matrix<double, -1, -1, 0, -1, -1>, 0> const, -1, 1, true> const>, Eigen::internal::evaluator_traits<Eigen::CwiseUnaryOp<Eigen::internal::scalar_multiple_op<double>, Eigen::Block<Eigen::Product<Eigen::Inverse<Eigen::Product<Eigen::Matrix<double, -1, -1, 0, -1, -1>, Eigen::Matrix<double, -1, -1, 0, -1, -1>, 0> >, Eigen::Matrix<double, -1, -1, 0, -1, -1>, 0> const, -1, 1, true> const> >::Shape>::value, void*>::type) (func=..., src=..., dst=...) at /usr/include/eigen3/Eigen/src/Core/AssignEvaluator.h:712
#31 Eigen::MatrixBase<Eigen::Matrix<double, -1, 1, 0, -1, 1> >::operator+=<Eigen::CwiseUnaryOp<Eigen::internal::scalar_multiple_op<double>, Eigen::Block<Eigen::Product<Eigen::Inverse<Eigen::Product<Eigen::Matrix<double, -1, -1, 0, -1, -1>, Eigen::Matrix<double, -1, -1, 0, -1, -1>, 0> >, Eigen::Matrix<double, -1, -1, 0, -1, -1>, 0> const, -1, 1, true> const> > (other=..., this=0x7fff8f7f66c0) at /usr/include/eigen3/Eigen/src/Core/CwiseBinaryOp.h:177
#32 Eigen::internal::gemv_dense_selector<2, 0, false>::run<Eigen::Product<Eigen::Inverse<Eigen::Product<Eigen::Matrix<double, -1, -1, 0, -1, -1>, Eigen::Matrix<double, -1, -1, 0, -1, -1>, 0> >, Eigen::Matrix<double, -1, -1, 0, -1, -1>, 0>, Eigen::Matrix<double, -1, 1, 0, -1, 1>, Eigen::Matrix<double, -1, 1, 0, -1, 1> > (alpha=<optimized out>, dest=..., rhs=..., lhs=...) at /usr/include/eigen3/Eigen/src/Core/GeneralProduct.h:357
#33 Eigen::internal::generic_product_impl<Eigen::Product<Eigen::Inverse<Eigen::Product<Eigen::Matrix<double, -1, -1, 0, -1, -1>, Eigen::Matrix<double, -1, -1, 0, -1, -1>, 0> >, Eigen::Matrix<double, -1, -1, 0, -1, -1>, 0>, Eigen::Matrix<double, -1, 1, 0, -1, 1>, Eigen::D---Type <return> to continue, or q <return> to quit---
enseShape, Eigen::DenseShape, 7>::scaleAndAddTo<Eigen::Matrix<double, -1, 1, 0, -1, 1> > (alpha=<optimized out>, rhs=..., lhs=..., dst=...) at /usr/include/eigen3/Eigen/src/Core/ProductEvaluators.h:349
#34 Eigen::internal::generic_product_impl_base<Eigen::Product<Eigen::Inverse<Eigen::Product<Eigen::Matrix<double, -1, -1, 0, -1, -1>, Eigen::Matrix<double, -1, -1, 0, -1, -1>, 0> >, Eigen::Matrix<double, -1, -1, 0, -1, -1>, 0>, Eigen::Matrix<double, -1, 1, 0, -1, 1>, Eigen::internal::generic_product_impl<Eigen::Product<Eigen::Inverse<Eigen::Product<Eigen::Matrix<double, -1, -1, 0, -1, -1>, Eigen::Matrix<double, -1, -1, 0, -1, -1>, 0> >, Eigen::Matrix<double, -1, -1, 0, -1, -1>, 0>, Eigen::Matrix<double, -1, 1, 0, -1, 1>, Eigen::DenseShape, Eigen::DenseShape, 7> >::scaleAndAddTo<Eigen::Matrix<double, -1, 1, 0, -1, 1> > (alpha=<optimized out>, rhs=..., lhs=..., dst=...) at /usr/include/eigen3/Eigen/src/Core/ProductEvaluators.h:334
#35 Eigen::internal::generic_product_impl_base<Eigen::Product<Eigen::Inverse<Eigen::Product<Eigen::Matrix<double, -1, -1, 0, -1, -1>, Eigen::Matrix<double, -1, -1, 0, -1, -1>, 0> >, Eigen::Matrix<double, -1, -1, 0, -1, -1>, 0>, Eigen::Matrix<double, -1, 1, 0, -1, 1>, Eigen::internal::generic_product_impl<Eigen::Product<Eigen::Inverse<Eigen::Product<Eigen::Matrix<double, -1, -1, 0, -1, -1>, Eigen::Matrix<double, -1, -1, 0, -1, -1>, 0> >, Eigen::Matrix<double, -1, -1, 0, -1, -1>, 0>, Eigen::Matrix<double, -1, 1, 0, -1, 1>, Eigen::DenseShape, Eigen::DenseShape, 7> >::evalTo<Eigen::Matrix<double, -1, 1, 0, -1, 1> > (dst=..., lhs=..., rhs=...) at /usr/include/eigen3/Eigen/src/Core/ProductEvaluators.h:322
#36 0x00007ffff433d3e1 in Eigen::internal::Assignment<Eigen::Matrix<double, -1, 1, 0, -1, 1>, Eigen::Product<Eigen::Product<Eigen::Inverse<Eigen::Product<Eigen::Matrix<double, -1, -1, 0, -1, -1>, Eigen::Matrix<double, -1, -1, 0, -1, -1>, 0> >, Eigen::Matrix<double, -1, -1, 0, -1, -1>, 0>, Eigen::Matrix<double, -1, 1, 0, -1, 1>, 0>, Eigen::internal::assign_op<double>, Eigen::internal::Dense2Dense, double>::run (src=..., dst=...) at /usr/include/eigen3/Eigen/src/Core/ProductEvaluators.h:133
#37 Eigen::internal::call_assignment_no_alias<Eigen::Matrix<double, -1, 1, 0, -1, 1>, Eigen::Product<Eigen::Product<Eigen::Inverse<Eigen::Product<Eigen::Matrix<double, -1, -1, 0, -1, -1>, Eigen::Matrix<double, -1, -1, 0, -1, -1>, 0> >, Eigen::Matrix<double, -1, -1, 0, -1, -1>, 0>, Eigen::Matrix<double, -1, 1, 0, -1, 1>, 0>, Eigen::internal::assign_op<double> > (func=..., src=..., dst=...) at /usr/include/eigen3/Eigen/src/Core/AssignEvaluator.h:747
#38 Eigen::PlainObjectBase<Eigen::Matrix<double, -1, 1, 0, -1, 1> >::_set_noalias<Eigen::Product<Eigen::Product<Eigen::Inverse<Eigen::Product<Eigen::Matrix<double, -1, -1, 0, -1, -1>, Eigen::Matrix<double, -1, -1, 0, -1, -1>, 0> >, Eigen::Matrix<double, -1, -1, 0, -1, -1>, 0>, Eigen::Matrix<double, -1, 1, 0, -1, 1>, 0> > (other=..., this=<optimized out>) at /usr/include/eigen3/Eigen/src/Core/PlainObjectBase.h:700
#39 Eigen::PlainObjectBase<Eigen::Matrix<double, -1, 1, 0, -1, 1> >::PlainObjectBase<Eigen::Product<Eigen::Product<Eigen::Inverse<Eigen::Product<Eigen::Matrix<double, -1, -1, 0, -1, -1>, Eigen::Matrix<double, -1, -1, 0, -1, -1>, 0> >, Eigen::Matrix<double, -1, -1, 0, -1, -1>, 0>, Eigen::Matrix<double, -1, 1, 0, -1, 1>, 0> > (other=..., this=0x7fff8f7f66c0) at /usr/include/eigen3/Eigen/src/Core/PlainObjectBase.h:510
#40 Eigen::Matrix<double, -1, 1, 0, -1, 1>::Matrix<Eigen::Product<Eigen::Product<Eigen::Inverse<Eigen::Product<Eigen::Matrix<double, -1, -1, 0, -1, -1>, Eigen::Matrix<double, -1, -1, 0, -1, -1>, 0> >, Eigen::Matrix<double, -1, -1, 0, -1, -1>, 0>, Eigen::Matrix<double, -1, 1, 0, -1, 1>, 0> > (other=..., this=0x7fff8f7f66c0) at /usr/include/eigen3/Eigen/src/Core/Matrix.h:379
#41 Segment::fitLocalLine (this=this@entry=0x7fffa819ecc0, points=...) at /home/alfredoso/Robotics/SCRThesis/Thesis_ws/src/linefit_ground_segmentation/linefit_ground_segmentation/src/segment.cc:145

#42 0x00007ffff433d6d7 in Segment::fitSegmentLines (this=0x7fffa819ecc0) at /home/alfredoso/Robotics/SCRThesis/Thesis_ws/src/linefit_ground_segmentation/linefit_ground_segmentation/src/segment.cc:42
#43 0x00007ffff4331ef8 in GroundSegmentation::lineFitThread (this=0x7fffbeff4060, start_index=<optimized out>, end_index=180, lines=0x0, lines_mutex=0x7fffbeff3e10)
    at /home/alfredoso/Robotics/SCRThesis/Thesis_ws/src/linefit_ground_segmentation/linefit_ground_segmentation/src/ground_segmentation.cc:118
#44 0x00007ffff4e0dc80 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#45 0x00007ffff60036fa in start_thread (arg=0x7fff8f7fe700) at pthread_create.c:333
#46 0x00007ffff487cb5d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
```

By doing some experiments, I found out that it is related to the way in which we solve the linear system for line fitting:

https://github.com/lorenwel/linefit_ground_segmentation/blob/11e4ed0090f7637a5929b3c56febe9a6687941ab/linefit_ground_segmentation/src/segment.cc#L145

I submitted a pull request to fix this, #6

**Comment by lorenwel** [comment]
Merged PR which fixed this.
